<?php

namespace Jazzyweb\AulasMentor\NotasFrontendBundle\JAMNotasFrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TarifaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifaRepository extends EntityRepository
{
}
